SELECT * FROM FN.view_melhores_cidades;
GO

SELECT * FROM FN.view_valor_imovel_ano;
GO

SELECT * FROM FN.view_custo_investimento;
GO

SELECT * FROM FN.view_margem_lucro;
GO

SELECT * FROM FN.view_melhor_epoca;
GO

SELECT * FROM FN.view_aluguel_cidade;
GO

SELECT * FROM FN.view_tempo_retorno;
GO

SELECT * FROM FN.view_juros_financiamento;
GO

SELECT * FROM FN.view_valorizacao_economia;
GO

SELECT * FROM FN.view_infra_impacto;
GO

SELECT * FROM FN.view_demografia_demanda;
GO
